feat:
NikAndDeg/java-shareit pull request #1
Opened 2024-03-28 11:25 UTC by NikAndDeg

2024-03-28 16:15 UTC, Fleaman777 requested changes

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorResponse.java
> +	String message;
поля должны быть private

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/FakeItemStorage.java
> +public class FakeItemStorage implements ItemStorage {
если это fake сторедж, зачем он нам тогда нужен) 
лучше переименовать в менее вызывающее

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/FakeItemStorage.java
> +		return itemList;
здесь отлично вписался бы стрим

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/FakeItemStorage.java
> +	}
здесь отлично

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +						   @RequestHeader("X-Sharer-User-Id") Integer userId) {
X-Sharer-User-Id - можно было бы вынести в константу

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +			throw new BadRequestException("Item without name or description or available.");
подобная проверка должна быть в слое сервис - тем самым мы разделим ответственность выполнения: 
контроллер - за принятие запросов
сервис - за логику

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +	@Autowired
можно явно не указывать конструктор (и аннотацию @Autowire над ним), что бы внедрить компоненты. 
Достаточно повесить аннотацию @RequiredArgыConstructor над классом и сделать поля final,

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +			log.info("Item not found. Item with id [{}] not exists.", itemId);
можно даже было бы повысить уровень логирования, например до warn 

и еще как вариант, вынести в эксепшен хэндлер, что бы не дублировать лог в разных местах

2024-03-28 16:15 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/user/FakeUserStorage.java
> +		);
аналагично, можно сделать через стрим

2024-03-28 22:13 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +			log.info("Item not found. Item with id [{}] not exists.", itemId);
Хм, логировать в хендлере мне и в голову не приходило, обмазгую! С одной стороны не надо одинаковые и похожие логи писать, а с другой мне нравится видеть логирование в месте, где что-то пошло не так. Пока хочу оставить как есть.

2024-03-29 10:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +			log.info("Item not found. Item with id [{}] not exists.", itemId);
да, хорошо, можешь оставить

как вариант, что бы различать где именно вылетела ошибка, можно передавать подходящий еррор месседж в эксепшен, который бы потом логировался в в хэндлере

2024-03-29 10:59 UTC, Fleaman777 approved these changes

2024-03-29 10:59 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorage.java
> +public class InMemoryItemStorage implements ItemStorage {
отлично)

2024-03-30 20:48 UTC, merged