Add bookings
NikAndDeg/java-shareit pull request #2
Opened 2024-05-30 11:12 UTC by NikAndDeg

2024-05-31 12:57 UTC, Fleaman777 requested changes

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +		Booking savedBooking = bookingRepository.save(booking);
метод изменяет состояние БД, правильней было бы его выполнять в транзакции, 

относится ко всем аналогичным местам

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +						LocalDateTime.now(),
LocalDateTime.now() - можно вынести в локальную переменную

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +				})
возможно чистая фкусовщина, но я бы лучше вынес в отдельный метод, для улучшения читаемости,

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +	}
почему бы в контроллере сразу не сделать тип boolean, 
в таком слуае, если вдруг клиент передаст невалидное boolean значение, то спринг сам вернет ошибку

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +		subgraphs = @NamedSubgraph(name = "item-owner-graph", attributeNodes = @NamedAttributeNode("owner"))
неплохо, очень нечатно попадаются работы, где решают применить EntityGrap )

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +	@ToString.Exclude
грамотно!

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  	private LocalDateTime start;
можно добавить аннотацию, которая будет просечивать дефолтное значение этому полю, когда будет создаваться запись

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +	//https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/
да это ж круто! (с) ))

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +		return itemIdComments;
выглядит так, как-будто можно было бы попробовать сделать этот метод через стрим

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +		return List.of(Optional.ofNullable(lastBooking), Optional.ofNullable(nextBooking));
попробуй часть логики этого метода вынести в отдельный метод, для лучшего восприятия

2024-05-31 12:57 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +		return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
в 99% случаях в качестве дефолтного ORM фреймворка оставляют хибернейт, 
но все равно, лучше всегда помнить, что в теории он может быть заменен, а значит, спцифичные для него вещи могут перестать работать

2024-05-31 12:57 UTC, Fleaman777 commented on src/test/resources/test_schema.sql
> +    booking_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
или здесь можно добавть установку дефолтного значения

2024-06-01 06:13 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +				})
Вынес компаратор в BookingDto

2024-06-01 06:16 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +		Booking savedBooking = bookingRepository.save(booking);
Пометил аннотацией @Transactional методы, которые изменяют состояние БД, во всех сервисах

2024-06-01 06:33 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +		return itemIdComments;
Теперь я знаю о существовании Collectors.groupingBy(

2024-06-01 06:38 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  	private LocalDateTime start;
![image](https://github.com/NikAndDeg/java-shareit/assets/137883498/288de457-9891-42c2-b6c8-8950408ec264)

По тестам в контроллер вроде везде передается BookingDto с стартом и концом

2024-06-01 06:50 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +		return List.of(Optional.ofNullable(lastBooking), Optional.ofNullable(nextBooking));
Думал и смотрел, но не смог найти способ разбить этот метод на несколько.
Мог бы разделить поиск lastBooking и nextBooking на два метода, но тогда бы по всем бронированиям пришлось бы проходить циклом дважды. А что еще вынести в отдельный метод не знаю)

2024-06-01 06:51 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +						LocalDateTime.now(),
сбацал-сделал

2024-06-01 06:52 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +	}
сделал-сбацал

2024-06-01 06:53 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +	//https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/
Я уважаю, что они делают, но я не понимаю.

2024-06-01 06:57 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +		return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
Наверное в будущем буду переписывать hashCode()  и equals() с использованием полей без ссылок на другие сущности, но пока я очень доволен, что нашел такую красоту, хоть и довольно туманно представляю, что происходит внутри этих решений)

2024-06-01 07:01 UTC, NikAndDeg commented on src/test/resources/test_schema.sql
> +    booking_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
Нашел DEFAULT NOW(), но, кажется, установка начала бронирования и конца относится к бизнес-слою приложения, и не хочется мне переносить это на слой БД.

2024-06-02 06:07 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
>  	private LocalDateTime start;
в теории могут появится новые способы создания бронирования, которые не будут передавать это значение. 
Но городить велосипед, думая, что когда-нибудь это может пригодиться, тоже не совсем правильно, так в коде может появиться много лишнего, 

так что оставляю это на твое усмотрение)

2024-06-02 06:09 UTC, Fleaman777 approved these changes

2024-06-03 07:22 UTC, merged