Написал тесты
NikAndDeg/java-shareit pull request #3
Opened 2024-06-10 10:07 UTC by NikAndDeg

2024-06-11 13:48 UTC, Fleaman777 requested changes

2024-06-11 13:48 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +	List<Item> findItemByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIs(String infix1,
какого-то единого бест практиса по поповду длины подобных методов не встречал, но очень длинные конечно не очень рекомендуется, как альтернатива использовать query

2024-06-11 13:48 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +		List<ItemRequest> requests = requestRepository.findWithItemsAllByRequesterId(requesterId);
можно сразу вызвать стрим на requestRepository.findWithItemsAllByRequesterId(requesterId), тк переменная requests особого смысла не добавляет

2024-06-11 13:48 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/util/Pagenator.java
> +}
хороший утильный класс, 
можно еще добавить аннотацю @UtilityClass, что бы создался приватный конструктор

2024-06-11 13:48 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/comment/CommentDtoMapperTest.java
> +	private final String text = "In the end, your friends are gonna let you down. Family. They're the ones you can depend on.";
можно было бы сделать констнтой

2024-06-11 13:48 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +	ItemRequestService requestService;
а чем это поле от других оотличется, так же можно сделать private

2024-06-11 13:48 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +}
общие вещи можно было бы вынести в константы и в отдельные методы

2024-06-11 14:33 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +	List<Item> findItemByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIs(String infix1,
Подумал, что где могу, делегирую написание запросов к JPA. Предикаты QueryDSL городить не хотелось, отправлять JPQL-запрос тоже как-то не очень, ибо запросных методов хватило для описания логики обращения к БД.
Могу написать через query, но не очень горю желанием)

P.S. Имеет ли смысл оставлять комментарий к подобным трудночитаемым методам с описанием чего они делают?

2024-06-11 14:40 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/util/Pagenator.java
> +}
Не знал, что есть такая аннотация, и что нужно приватный конструктор делать для утилитарных классов. Погуглил, почитал. Спасибо за замечание!

2024-06-11 14:50 UTC, NikAndDeg commented on src/test/java/ru/practicum/shareit/item/comment/CommentDtoMapperTest.java
> +	private final String text = "In the end, your friends are gonna let you down. Family. They're the ones you can depend on.";
Прошелся по тестам для мапперов и бабахнул

2024-06-11 14:50 UTC, NikAndDeg commented on src/test/java/ru/practicum/shareit/request/ItemRequestControllerTest.java
> +	ItemRequestService requestService;
Ничем, я просто забыл)

2024-06-11 14:50 UTC, NikAndDeg commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +		List<ItemRequest> requests = requestRepository.findWithItemsAllByRequesterId(requesterId);
Бабахнул!

2024-06-11 14:54 UTC, NikAndDeg commented on src/test/java/ru/practicum/shareit/user/UserServiceImplTest.java
> +}
"Можно" это же не "нужно", оставлю так, неохота перебирать все тесты на сервисы и выносить значения в константы)

Но на будущее буду выносить в константы и методы!

2024-06-13 05:58 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +	List<Item> findItemByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIs(String infix1,
хах, 
мне кажется многие сказали бы, имеет смысл не доводить до такого)) 

ну а если написано, то можно оставить, разработчик уже сам потом решит, читать коммент или нет, а так хоть альтернативный вариант восприятия будет )

2024-06-13 06:00 UTC, Fleaman777 approved these changes

2024-07-01 07:45 UTC, merged