Разделил приложение на модули, настроил docker
NikAndDeg/java-shareit pull request #4
Opened 2024-07-04 08:13 UTC by NikAndDeg

2024-07-05 09:15 UTC, Fleaman777 requested changes

2024-07-05 09:15 UTC, Fleaman777 commented on docker-compose.yaml
> +    image: postgres:13.7-alpine
хорошо, что указываешь конкретную версию имеджа, а не просто latest,
так безопасней, т.к. меньше шансов нарваться на версию базового имеджа, с которым текущая версия приложения не будет работать,
то же относится и к Dockerfile

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private String bookingPath;
Переменные c @Value хорошо бы сделать final, что бы гарантировать их неизменяемость.

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private final WebClient client = WebClient.create();
В дефолтной реализации когда контроллер имеет скоуп singletone, должно работать все нормально,

но если будет prototype или request/session то создание WebClient.create() при каждом запросе может приводить к лишним накладным расходам. Лучше создать один экземпляр WebClient и использовать его повторно.
можно через spring java config с использованием @configuration и @bean

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	}
вообще по хорошему, лучше логику вызовов других сервисов и прием новыз запросов разделять по разным классам, 
так будет выполнятеся SRP принцип и код в будещем будет проще расширять

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public Map<String, String> handleBookingUnsupportedStatus(final BookingUnsupportedStatus exception) {
как вариант на улучшение, метод handleBookingUnsupportedStatus можно обновить, добавив кастомный объект ответа, который будет содержать больше информации об ошибке.

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	}
этот метод можно попробовать реализовать через стрим

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +}
аналагично с комментариями для booking в этом контроллере и в след

2024-07-05 09:15 UTC, Fleaman777 commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://${SHARE_IT_SERVER_HOST}:${SHARE_IT_SERVER_PORT}
респет за такую конструкцию, можно ее еще немного апгрейднуть, через : добавить дефолтное значение, которое будет использоваться если переменная не будет установалена в докер компосе и тп
POSTGRES_USER:test

2024-07-07 07:31 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private String bookingPath;
Не получится. IDEA выдает "Variable 'shareItServerUrl' might not have been initialized"

2024-07-07 09:01 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	private final WebClient client = WebClient.create();
Впервые появился повод использовать @configuration и @bean, спасибо за комменатрий!

2024-07-07 09:06 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public Map<String, String> handleBookingUnsupportedStatus(final BookingUnsupportedStatus exception) {
Перенес в ErrorHandler. Объект ответа ErrorResponse решил не писать, ибо не придумал, какую еще полезную инфу в ответ добавить. Если будет много полей у ответа, то напишу ErrorResponse.

2024-07-07 10:13 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	}
Задача тривиальна, но я как-то закипел головой, и не могу сообразить что к чему. Я высплюсь и обязательно сделаю это в стриме)

2024-07-08 04:49 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	public Map<String, String> handleBookingUnsupportedStatus(final BookingUnsupportedStatus exception) {
Перенес в ErrorHandler.  Не придумал, какую еще информацию об ошибке вернуть, поэтому оставил мапу. Если у ответа будет много полей, то добавлю кастомный объект, а пока оставлю так)

2024-07-08 04:50 UTC, NikAndDeg commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +	}
Надеюсь, правильно понял комментарий)

2024-07-08 04:52 UTC, NikAndDeg commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://${SHARE_IT_SERVER_HOST}:${SHARE_IT_SERVER_PORT}
В качестве дефолтных значений в gateway поставил настройки по подключению к server. У server -- подключение к локальному репозиторию.

2024-07-08 07:01 UTC, Fleaman777 approved these changes

2024-07-08 07:54 UTC, merged